# $FreeBSD$

compute_engine_instance:
  platform: freebsd
  image_project: freebsd-org-cloud-dev
  image: freebsd-13-0-release-amd64
  cpu: 7
  memory: 8G
  disk: 40

task:
  name: Build aquaBSD base and kernel for 'amd64' target
  env:
    TARGET: amd64
    TARGET_ARCH: amd64
  timeout_in: 120m
  install_script:
  - pkg install -y qemu llvm12
  setup_script:
  - uname -a
  - df -h
  - pkg --version
  - pw useradd user
  - mkdir -p /usr/obj/$(pwd -P)
  - chown user:user /usr/obj/$(pwd -P)
  kernel_build_script:
  - su user -c "make -j$(sysctl -n hw.ncpu) CROSS_TOOLCHAIN=llvm12 WITHOUT_TOOLCHAIN=yes WITHOUT_LIB32=yes WITHOUT_TCSH=yes WITHOUT_FREEBSD_UPDATE=yes buildkernel"
  base_build_script:
  - su user -c "make -j$(sysctl -n hw.ncpu) CROSS_TOOLCHAIN=llvm12 WITHOUT_TOOLCHAIN=yes WITHOUT_LIB32=yes WITHOUT_TCSH=yes WITHOUT_FREEBSD_UPDATE=yes buildworld"
  release_script:
  - su user -c "cd release/ && make CROSS_TOOLCHAIN=llvm12 WITHOUT_TOOLCHAIN=yes WITHOUT_LIB32=yes WITHOUT_TCSH=yes WITHOUT_FREEBSD_UPDATE=yes -DNO_ROOT -DNODOCS -DNOPORTS -DNOSRC kernel.txz base.txz"
  post_script:
  - ls -l /usr/obj/usr/src/amd64.amd64/release/
  - df -h
  - du -h -s /usr/obj
  distribution_artifacts:
    path: "/usr/obj/usr/src/amd64.amd64/release/kernel.txz"
    path: "/usr/obj/usr/src/amd64.amd64/release/base.txz"