# $FreeBSD$

compute_engine_instance:
  platform: freebsd
  image_project: freebsd-org-cloud-dev
  image: freebsd-13-0-release-amd64
  cpu: 6
  memory: 8G
  disk: 40

task:
  name: Build aquaBSD base and kernel for 'amd64' target
  env:
    TARGET: amd64
    TARGET_ARCH: amd64
  timeout_in: 120m
  work_dir_script: # TODO: include in 'setup_script'
  - export WORK_DIR=$(pwd -P)
  setup_script:
  - uname -a
  - df -h
  - pkg --version
  - pw useradd user
  - mkdir -p /usr/obj/$WORK_DIR
  - chown user:user /usr/obj/$WORK_DIR
  kernel_build_script:
  - su user -c "make -j$(sysctl -n hw.ncpu) WITHOUT_TOOLCHAIN=yes WITHOUT_LIB32=yes WITHOUT_TCSH=yes WITHOUT_FREEBSD_UPDATE=yes buildkernel"
  base_build_script:
  - su user -c "make -j$(sysctl -n hw.ncpu) WITHOUT_TOOLCHAIN=yes WITHOUT_LIB32=yes WITHOUT_TCSH=yes WITHOUT_FREEBSD_UPDATE=yes buildworld"
  release_script:
  - su user -c "cd release/ && make WITHOUT_TOOLCHAIN=yes WITHOUT_LIB32=yes WITHOUT_TCSH=yes WITHOUT_FREEBSD_UPDATE=yes -DNO_ROOT -DNODOCS -DNOPORTS -DNOSRC kernel.txz base.txz src.txz"
  post_script:
  - ls -l /usr/obj/$WORK_DIR/amd64.amd64/release/
  - df -h
  - du -h -s /usr/obj
  distribution_artifacts:
    path: "/usr/obj/$WORK_DIR/amd64.amd64/release/kernel.txz"
    path: "/usr/obj/$WORK_DIR/amd64.amd64/release/base.txz"
    path: "/usr/obj/$WORK_DIR/amd64.amd64/release/src.txz"
