# $FreeBSD$

compute_engine_instance:
  platform: freebsd
  image_project: freebsd-org-cloud-dev
  image: freebsd-13-0-release-amd64
  cpu: 8
  memory: 8G
  disk: 40

task:
  name: Build aquaBSD base and kernel for 'amd64' target
  env:
    TARGET: amd64
    TARGET_ARCH: amd64
  timeout_in: 120m
  setup_script:
  - uname -a
  - df -h
  - pkg --version
  - sh ci/setup.sh $(pwd -P)
  kernel_build_script:
  - sh ci/kernel.sh $(pwd -P)
  base_build_script:
  - sh ci/base.sh $(pwd -P)
  distribute_script:
  - sh ci/distribute.sh $(pwd -P)
  package_script:
  - sh ci/package.sh $(pwd -P)
  post_script:
  - ls -l artifacts
  - df -h
  - du -h -s /usr/obj
  distribution_artifacts:
    path: "artifacts/*"
